### ISSUE TITLE
Configuration fails with Joomla 2.5.28 and Virtumart 2.0.2 and Icepay version 1.0.1

### ISSUE THREAD

**Issue by vincentmakayama** [ICEPAYdev/VirtueMart-3#1]
The configuration tab is empty, showing only this notice: 

Undefined property: JSimpleXMLElement::$params in /public/sites/www.makayama.net/libraries/joomla/html/parameter.php on line 398

**Comment by tsygankov** [comment]
Hi vincentmakayama,

This payment module is compatible only with VirtueMart 3.0.9. Please try installing ICEPAY Payment Module for VirtueMart 2. You can download the latest version [here](https://icepay.com/nl/en/webshop-modules/virtuemart-2/).

**Comment by tsygankov** [comment]
I hope your problem is solved. Please let me know if you have any other questions.
